---
- hosts: all
  become: true
  tasks:
    - name: Debug actual date_time
      debug:
        msg: "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"

    - name: Set new timezone
      timezone:
        name: "{{ new_timezone }}"

    - name: Wait for the previous task to take effect
      wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Debug new date_time
      debug:
        msg: "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
